/**
 * Maths-diagnostic item bank.
 *
 * Canonical source for the item bank used by the in-process LangGraph
 * agent in `apps/web/`. Lives in `packages/core` so the web app and any
 * future tooling can import it without coupling to the route handler.
 */
import type { Item } from './types';

export const ITEMS: Item[] = [
  {
    id: 'jc-nu-001',
    stage: 'junior_cycle',
    strand: 'number',
    learningOutcome: 'JC.NU.U.1: Recall and apply basic multiplication facts',
    b: -2,
    text: 'What is $7 \\times 8$?',
    choices: ['54', '56', '63', '49'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Multiplication facts',
  },
  {
    id: 'jc-nu-002',
    stage: 'junior_cycle',
    strand: 'number',
    learningOutcome: 'JC.NU.U.2: Identify prime numbers up to 50',
    b: -2,
    text: 'Which of the following is a prime number?',
    choices: ['9', '15', '21', '23'],
    correctIndex: 3,
    source: 'anchor',
    khanAcademyRef: 'KA: Prime numbers',
  },
  {
    id: 'jc-nu-003',
    stage: 'junior_cycle',
    strand: 'number',
    learningOutcome: 'JC.NU.U.3: Calculate percentages of quantities',
    b: -1,
    text: 'What is $25\\%$ of $80$?',
    choices: ['15', '20', '25', '40'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Percentages',
  },
  {
    id: 'jc-nu-004',
    stage: 'junior_cycle',
    strand: 'number',
    learningOutcome: 'JC.NU.O.4: Add and subtract fractions with different denominators',
    b: 0,
    text: 'Evaluate $\\frac{2}{3} + \\frac{1}{4}$.',
    choices: ['$\\frac{3}{7}$', '$\\frac{3}{12}$', '$\\frac{11}{12}$', '$\\frac{8}{12}$'],
    correctIndex: 2,
    source: 'anchor',
    khanAcademyRef: 'KA: Adding fractions with unlike denominators',
  },
  {
    id: 'jc-nu-005',
    stage: 'junior_cycle',
    strand: 'number',
    learningOutcome: 'JC.NU.H.5: Apply ratios to share quantities',
    b: 1,
    text: 'Two friends share \u20ac120 in the ratio $3 : 5$. How much does the friend with the larger share receive?',
    choices: ['\u20ac45', '\u20ac60', '\u20ac75', '\u20ac80'],
    correctIndex: 2,
    source: 'anchor',
    khanAcademyRef: 'KA: Ratios and proportions',
  },
  {
    id: 'jc-nu-006',
    stage: 'junior_cycle',
    strand: 'number',
    learningOutcome: 'JC.NU.H.6: Simplify expressions involving surds',
    b: 2,
    text: 'Simplify $\\sqrt{50} + \\sqrt{18}$ in the form $a\\sqrt{2}$.',
    choices: ['$5\\sqrt{2}$', '$8\\sqrt{2}$', '$\\sqrt{68}$', '$13\\sqrt{2}$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Simplifying square roots',
  },
  {
    id: 'jc-al-001',
    stage: 'junior_cycle',
    strand: 'algebra',
    learningOutcome: 'JC.AL.U.1: Evaluate algebraic expressions for given values',
    b: -2,
    text: 'If $x = 4$, what is the value of $3x + 2$?',
    choices: ['12', '14', '9', '24'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Evaluating expressions',
  },
  {
    id: 'jc-al-002',
    stage: 'junior_cycle',
    strand: 'algebra',
    learningOutcome: 'JC.AL.U.2: Solve linear equations with one variable',
    b: -1,
    text: 'Solve for $x$: $2x + 3 = 11$.',
    choices: ['$x = 3$', '$x = 4$', '$x = 5$', '$x = 7$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Linear equations 1',
  },
  {
    id: 'jc-al-003',
    stage: 'junior_cycle',
    strand: 'algebra',
    learningOutcome: 'JC.AL.O.3: Expand binomial products',
    b: -1,
    text: 'Expand $(x + 3)(x - 2)$.',
    choices: ['$x^2 + x - 6$', '$x^2 - x - 6$', '$x^2 + 5x - 6$', '$x^2 - 6$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Multiplying binomials',
  },
  {
    id: 'jc-al-004',
    stage: 'junior_cycle',
    strand: 'algebra',
    learningOutcome: 'JC.AL.O.4: Factorise quadratic expressions',
    b: 0,
    text: 'Factorise $x^2 - 5x + 6$.',
    choices: [
      '$(x - 1)(x - 6)$',
      '$(x - 2)(x - 3)$',
      '$(x + 2)(x + 3)$',
      '$(x - 5)(x + 1)$',
    ],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Factoring quadratics 1',
  },
  {
    id: 'jc-al-005',
    stage: 'junior_cycle',
    strand: 'algebra',
    learningOutcome: 'JC.AL.H.5: Solve simultaneous linear equations',
    b: 1,
    text: 'Solve the system: $x + y = 7$ and $x - y = 1$.',
    choices: [
      '$x = 3, y = 4$',
      '$x = 4, y = 3$',
      '$x = 5, y = 2$',
      '$x = 2, y = 5$',
    ],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Systems of equations',
  },
  {
    id: 'jc-al-006',
    stage: 'junior_cycle',
    strand: 'algebra',
    learningOutcome:
      'JC.AL.H.6: Solve quadratic equations using the quadratic formula or factorisation',
    b: 2,
    text: 'Find the solutions of $x^2 - 4x - 5 = 0$.',
    choices: [
      '$x = 1, x = 5$',
      '$x = -1, x = 5$',
      '$x = -1, x = -5$',
      '$x = 1, x = -5$',
    ],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Solving quadratics by factoring',
  },
  {
    id: 'jc-gt-001',
    stage: 'junior_cycle',
    strand: 'geometry_trig',
    learningOutcome: 'JC.GT.U.1: Recall properties of angles on a straight line',
    b: -2,
    text: 'Two angles lie on a straight line. One is $110^\\circ$. What is the other?',
    choices: ['$70^\\circ$', '$80^\\circ$', '$90^\\circ$', '$110^\\circ$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Angles on a straight line',
  },
  {
    id: 'jc-gt-002',
    stage: 'junior_cycle',
    strand: 'geometry_trig',
    learningOutcome: 'JC.GT.U.2: Calculate the area of a rectangle',
    b: -1,
    text: 'A rectangle has length $8\\,\\text{cm}$ and width $5\\,\\text{cm}$. What is its area?',
    choices: [
      '$13\\,\\text{cm}^2$',
      '$26\\,\\text{cm}^2$',
      '$40\\,\\text{cm}^2$',
      '$45\\,\\text{cm}^2$',
    ],
    correctIndex: 2,
    source: 'anchor',
    khanAcademyRef: 'KA: Area of rectangles',
  },
  {
    id: 'jc-gt-003',
    stage: 'junior_cycle',
    strand: 'geometry_trig',
    learningOutcome: 'JC.GT.O.3: Apply the Pythagorean theorem in right-angled triangles',
    b: 0,
    text: 'A right-angled triangle has legs of length $3$ and $4$. What is the length of the hypotenuse?',
    choices: ['$5$', '$6$', '$7$', '$\\sqrt{7}$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Pythagorean theorem',
  },
  {
    id: 'jc-gt-004',
    stage: 'junior_cycle',
    strand: 'geometry_trig',
    learningOutcome: 'JC.GT.O.4: Calculate the volume of a cuboid',
    b: 0,
    text: 'A cuboid has dimensions $4\\,\\text{cm} \\times 3\\,\\text{cm} \\times 2\\,\\text{cm}$. What is its volume?',
    choices: [
      '$9\\,\\text{cm}^3$',
      '$12\\,\\text{cm}^3$',
      '$24\\,\\text{cm}^3$',
      '$26\\,\\text{cm}^3$',
    ],
    correctIndex: 2,
    source: 'anchor',
    khanAcademyRef: 'KA: Volume of rectangular prisms',
  },
  {
    id: 'jc-gt-005',
    stage: 'junior_cycle',
    strand: 'geometry_trig',
    learningOutcome: 'JC.GT.H.5: Apply trigonometric ratios in right-angled triangles',
    b: 1,
    text: 'In a right-angled triangle, the side opposite an angle of $30^\\circ$ has length $5$. What is the length of the hypotenuse?',
    choices: ['$2.5$', '$5\\sqrt{3}$', '$10$', '$\\frac{5}{2}\\sqrt{3}$'],
    correctIndex: 2,
    source: 'anchor',
    khanAcademyRef: 'KA: Trigonometric ratios in right triangles',
  },
  {
    id: 'jc-gt-006',
    stage: 'junior_cycle',
    strand: 'geometry_trig',
    learningOutcome: 'JC.GT.H.6: Use coordinate geometry to find the distance between two points',
    b: 2,
    text: 'Find the distance between the points $A(1, 2)$ and $B(4, 6)$.',
    choices: ['$5$', '$7$', '$\\sqrt{7}$', '$\\sqrt{25} - 1$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Distance formula',
  },
  {
    id: 'jc-fn-001',
    stage: 'junior_cycle',
    strand: 'functions',
    learningOutcome: 'JC.FN.U.1: Evaluate a function at a given input',
    b: -2,
    text: 'If $f(x) = 2x + 1$, what is $f(3)$?',
    choices: ['$5$', '$6$', '$7$', '$9$'],
    correctIndex: 2,
    source: 'anchor',
    khanAcademyRef: 'KA: Evaluating functions',
  },
  {
    id: 'jc-fn-002',
    stage: 'junior_cycle',
    strand: 'functions',
    learningOutcome: 'JC.FN.U.2: Identify the slope of a linear function',
    b: -1,
    text: 'What is the slope of the line $y = 4x - 7$?',
    choices: ['$-7$', '$4$', '$-4$', '$\\frac{1}{4}$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Slope-intercept form',
  },
  {
    id: 'jc-fn-003',
    stage: 'junior_cycle',
    strand: 'functions',
    learningOutcome: 'JC.FN.O.3: Find the y-intercept of a linear function',
    b: 0,
    text: 'Where does the line $y = -2x + 5$ cross the y-axis?',
    choices: ['$(0, -2)$', '$(0, 5)$', '$(5, 0)$', '$(-2, 5)$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Y-intercept',
  },
  {
    id: 'jc-fn-004',
    stage: 'junior_cycle',
    strand: 'functions',
    learningOutcome: 'JC.FN.H.4: Find the roots of a quadratic function',
    b: 1,
    text: 'What are the roots of $f(x) = x^2 - 9$?',
    choices: ['$x = 3$ only', '$x = -3$ only', '$x = \\pm 3$', '$x = \\pm 9$'],
    correctIndex: 2,
    source: 'anchor',
    khanAcademyRef: 'KA: Zeros of quadratic functions',
  },
  {
    id: 'jc-fn-005',
    stage: 'junior_cycle',
    strand: 'functions',
    learningOutcome: 'JC.FN.H.5: Combine evaluation with algebraic manipulation of functions',
    b: 1,
    text: 'If $f(x) = x^2 - 2x$, what is $f(-3)$?',
    choices: ['$3$', '$15$', '$-3$', '$9$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Evaluating functions',
  },
  {
    id: 'jc-fn-006',
    stage: 'junior_cycle',
    strand: 'functions',
    learningOutcome: 'JC.FN.H.6: Identify the vertex of a quadratic function in vertex form',
    b: 2,
    text: 'What is the vertex of the parabola $y = (x - 2)^2 + 3$?',
    choices: ['$(2, 3)$', '$(-2, 3)$', '$(2, -3)$', '$(-2, -3)$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Vertex form of a quadratic',
  },
  {
    id: 'jc-sp-001',
    stage: 'junior_cycle',
    strand: 'statistics_prob',
    learningOutcome: 'JC.SP.U.1: Calculate the mean of a small data set',
    b: -2,
    text: 'Find the mean of the data: $4, 6, 8, 10$.',
    choices: ['$6$', '$7$', '$8$', '$28$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Mean, median, mode',
  },
  {
    id: 'jc-sp-002',
    stage: 'junior_cycle',
    strand: 'statistics_prob',
    learningOutcome: 'JC.SP.U.2: Identify the median of a small data set',
    b: -1,
    text: 'What is the median of the data: $3, 7, 9, 12, 15$?',
    choices: ['$7$', '$9$', '$12$', '$9.2$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Mean, median, mode',
  },
  {
    id: 'jc-sp-003',
    stage: 'junior_cycle',
    strand: 'statistics_prob',
    learningOutcome: 'JC.SP.O.3: Calculate simple probability of equally likely events',
    b: 0,
    text: 'A fair six-sided die is rolled. What is the probability of rolling an even number?',
    choices: ['$\\frac{1}{6}$', '$\\frac{1}{3}$', '$\\frac{1}{2}$', '$\\frac{2}{3}$'],
    correctIndex: 2,
    source: 'anchor',
    khanAcademyRef: 'KA: Basic probability',
  },
  {
    id: 'jc-sp-004',
    stage: 'junior_cycle',
    strand: 'statistics_prob',
    learningOutcome: 'JC.SP.O.4: Determine the range of a data set',
    b: 1,
    text: 'Find the range of the data: $5, 12, 7, 18, 3, 14$.',
    choices: ['$3$', '$15$', '$18$', '$11$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Range of a data set',
  },
  {
    id: 'jc-sp-005',
    stage: 'junior_cycle',
    strand: 'statistics_prob',
    learningOutcome: 'JC.SP.H.5: Calculate probabilities involving combined sample spaces',
    b: 2,
    text: 'Two fair coins are tossed. What is the probability of getting exactly one head?',
    choices: ['$\\frac{1}{4}$', '$\\frac{1}{3}$', '$\\frac{1}{2}$', '$\\frac{3}{4}$'],
    correctIndex: 2,
    source: 'anchor',
    khanAcademyRef: 'KA: Probability with combined events',
  },
  {
    id: 'jc-sp-006',
    stage: 'junior_cycle',
    strand: 'statistics_prob',
    learningOutcome: 'JC.SP.H.6: Interpret correlation from a scatter plot',
    b: 2,
    text: 'A scatter plot shows that as the number of hours studied increases, exam scores tend to increase. Which best describes the correlation?',
    choices: [
      'Strong negative correlation',
      'Strong positive correlation',
      'No correlation',
      'Perfect negative correlation',
    ],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Correlation coefficient intuition',
  },
  // -- number: easy/medium/hard expansion --
  {
    id: 'jc-nu-int-e-1',
    stage: 'junior_cycle',
    strand: 'number',
    learningOutcome: 'JC.NU.U.7: Apply order of operations to integers',
    b: -2,
    text: 'Evaluate $6 + 3 \\times 4$.',
    choices: ['18', '36', '24', '12'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Order of operations',
  },
  {
    id: 'jc-nu-int-e-2',
    stage: 'junior_cycle',
    strand: 'number',
    learningOutcome: 'JC.NU.U.8: Add and subtract signed integers',
    b: -2,
    text: 'Evaluate $-7 + 12$.',
    choices: ['$-5$', '$5$', '$19$', '$-19$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Adding negative numbers',
  },
  {
    id: 'jc-nu-pct-e-1',
    stage: 'junior_cycle',
    strand: 'number',
    learningOutcome: 'JC.NU.U.9: Calculate simple percentages',
    b: -1,
    text: 'What is $10\\%$ of $250$?',
    choices: ['$2.5$', '$25$', '$50$', '$250$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Percentages',
  },
  {
    id: 'jc-nu-frac-m-1',
    stage: 'junior_cycle',
    strand: 'number',
    learningOutcome: 'JC.NU.O.7: Multiply fractions',
    b: -1,
    text: 'Evaluate $\\frac{3}{4} \\times \\frac{2}{5}$.',
    choices: ['$\\frac{6}{20}$', '$\\frac{5}{9}$', '$\\frac{3}{10}$', '$\\frac{6}{9}$'],
    correctIndex: 2,
    source: 'anchor',
    khanAcademyRef: 'KA: Multiplying fractions',
  },
  {
    id: 'jc-nu-pct-m-1',
    stage: 'junior_cycle',
    strand: 'number',
    learningOutcome: 'JC.NU.O.8: Apply percentage increase',
    b: 0,
    text: 'A jacket costs \u20ac80 and is increased by $15\\%$. What is the new price?',
    choices: ['\u20ac92', '\u20ac95', '\u20ac68', '\u20ac115'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Percentage increase',
  },
  {
    id: 'jc-nu-rat-m-1',
    stage: 'junior_cycle',
    strand: 'number',
    learningOutcome: 'JC.NU.O.9: Apply simple ratios',
    b: 0,
    text: 'Divide $50$ in the ratio $2 : 3$. What is the smaller share?',
    choices: ['$10$', '$20$', '$25$', '$30$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Ratios',
  },
  {
    id: 'jc-nu-rat-h-1',
    stage: 'junior_cycle',
    strand: 'number',
    learningOutcome: 'JC.NU.H.7: Solve proportional reasoning problems',
    b: 1,
    text: 'If $5$ workers paint a wall in $12$ hours, how long would $4$ workers take at the same rate?',
    choices: ['$10$ hours', '$15$ hours', '$9.6$ hours', '$48$ hours'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Inverse proportion',
  },
  {
    id: 'jc-nu-ind-h-1',
    stage: 'junior_cycle',
    strand: 'number',
    learningOutcome: 'JC.NU.H.8: Apply laws of indices',
    b: 1,
    text: 'Simplify $2^3 \\times 2^4$.',
    choices: ['$2^7$', '$2^{12}$', '$4^7$', '$2^1$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Properties of exponents',
  },
  {
    id: 'jc-nu-sur-h-1',
    stage: 'junior_cycle',
    strand: 'number',
    learningOutcome: 'JC.NU.H.9: Simplify surds',
    b: 2,
    text: 'Simplify $\\sqrt{75}$ in the form $a\\sqrt{b}$.',
    choices: ['$5\\sqrt{3}$', '$3\\sqrt{5}$', '$25\\sqrt{3}$', '$\\sqrt{15}$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Simplifying square roots',
  },
  // -- algebra: easy/medium/hard expansion --
  {
    id: 'jc-al-eval-e-1',
    stage: 'junior_cycle',
    strand: 'algebra',
    learningOutcome: 'JC.AL.U.7: Evaluate simple algebraic expressions',
    b: -2,
    text: 'If $a = 5$, what is the value of $a - 2$?',
    choices: ['$3$', '$7$', '$10$', '$-3$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Evaluating expressions',
  },
  {
    id: 'jc-al-eval-e-2',
    stage: 'junior_cycle',
    strand: 'algebra',
    learningOutcome: 'JC.AL.U.8: Substitute integers into linear expressions',
    b: -2,
    text: 'If $y = 2$, evaluate $5y - 3$.',
    choices: ['$7$', '$10$', '$13$', '$5$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Evaluating expressions',
  },
  {
    id: 'jc-al-lin-e-1',
    stage: 'junior_cycle',
    strand: 'algebra',
    learningOutcome: 'JC.AL.U.9: Solve one-step linear equations',
    b: -1,
    text: 'Solve for $x$: $x - 5 = 9$.',
    choices: ['$x = 4$', '$x = 14$', '$x = -4$', '$x = 45$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: One-step equations',
  },
  {
    id: 'jc-al-lin-m-1',
    stage: 'junior_cycle',
    strand: 'algebra',
    learningOutcome: 'JC.AL.O.7: Solve linear equations with brackets',
    b: -1,
    text: 'Solve for $x$: $3(x - 2) = 12$.',
    choices: ['$x = 2$', '$x = 6$', '$x = 4$', '$x = 10$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Linear equations 2',
  },
  {
    id: 'jc-al-exp-m-1',
    stage: 'junior_cycle',
    strand: 'algebra',
    learningOutcome: 'JC.AL.O.8: Expand a binomial squared',
    b: 0,
    text: 'Expand $(x + 4)^2$.',
    choices: [
      '$x^2 + 16$',
      '$x^2 + 4x + 16$',
      '$x^2 + 8x + 16$',
      '$x^2 + 8x + 8$',
    ],
    correctIndex: 2,
    source: 'anchor',
    khanAcademyRef: 'KA: Squaring binomials',
  },
  {
    id: 'jc-al-fact-m-1',
    stage: 'junior_cycle',
    strand: 'algebra',
    learningOutcome: 'JC.AL.O.9: Factorise quadratic expressions with positive coefficients',
    b: 0,
    text: 'Factorise $x^2 + 5x + 6$.',
    choices: [
      '$(x + 1)(x + 6)$',
      '$(x + 2)(x + 3)$',
      '$(x - 2)(x - 3)$',
      '$(x + 5)(x + 1)$',
    ],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Factoring quadratics 1',
  },
  {
    id: 'jc-al-sim-h-1',
    stage: 'junior_cycle',
    strand: 'algebra',
    learningOutcome: 'JC.AL.H.7: Solve simultaneous linear equations by elimination',
    b: 1,
    text: 'Solve the system: $2x + y = 8$ and $x - y = 1$.',
    choices: [
      '$x = 3, y = 2$',
      '$x = 2, y = 4$',
      '$x = 1, y = 6$',
      '$x = 4, y = 0$',
    ],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Systems of equations',
  },
  {
    id: 'jc-al-quad-h-1',
    stage: 'junior_cycle',
    strand: 'algebra',
    learningOutcome: 'JC.AL.H.8: Solve quadratic equations by factorisation',
    b: 1,
    text: 'Solve $x^2 - 7x + 12 = 0$.',
    choices: [
      '$x = 3, x = 4$',
      '$x = -3, x = -4$',
      '$x = 2, x = 6$',
      '$x = 1, x = 12$',
    ],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Solving quadratics by factoring',
  },
  {
    id: 'jc-al-quad-h-2',
    stage: 'junior_cycle',
    strand: 'algebra',
    learningOutcome: 'JC.AL.H.9: Solve quadratics using the quadratic formula',
    b: 2,
    text: 'Solve $2x^2 - 5x - 3 = 0$.',
    choices: [
      '$x = 3, x = -\\frac{1}{2}$',
      '$x = -3, x = \\frac{1}{2}$',
      '$x = 3, x = \\frac{1}{2}$',
      '$x = -3, x = -\\frac{1}{2}$',
    ],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Quadratic formula',
  },
  // -- geometry_trig: easy/medium/hard expansion --
  {
    id: 'jc-gt-ang-e-1',
    stage: 'junior_cycle',
    strand: 'geometry_trig',
    learningOutcome: 'JC.GT.U.7: Recognise the sum of angles in a triangle',
    b: -2,
    text: 'A triangle has two angles of $40^\\circ$ and $60^\\circ$. What is the third angle?',
    choices: ['$60^\\circ$', '$70^\\circ$', '$80^\\circ$', '$100^\\circ$'],
    correctIndex: 2,
    source: 'anchor',
    khanAcademyRef: 'KA: Angles in a triangle',
  },
  {
    id: 'jc-gt-ang-e-2',
    stage: 'junior_cycle',
    strand: 'geometry_trig',
    learningOutcome: 'JC.GT.U.8: Identify vertically opposite angles',
    b: -2,
    text: 'Two lines cross. One angle formed is $55^\\circ$. What is the vertically opposite angle?',
    choices: ['$35^\\circ$', '$55^\\circ$', '$125^\\circ$', '$90^\\circ$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Vertical angles',
  },
  {
    id: 'jc-gt-per-e-1',
    stage: 'junior_cycle',
    strand: 'geometry_trig',
    learningOutcome: 'JC.GT.U.9: Calculate the perimeter of a rectangle',
    b: -1,
    text: 'A rectangle has length $9\\,\\text{cm}$ and width $4\\,\\text{cm}$. What is its perimeter?',
    choices: ['$13\\,\\text{cm}$', '$26\\,\\text{cm}$', '$36\\,\\text{cm}$', '$18\\,\\text{cm}$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Perimeter of rectangles',
  },
  {
    id: 'jc-gt-cir-m-1',
    stage: 'junior_cycle',
    strand: 'geometry_trig',
    learningOutcome: 'JC.GT.O.7: Calculate the circumference of a circle',
    b: -1,
    text: 'A circle has radius $7\\,\\text{cm}$. What is its circumference (leave the answer in terms of $\\pi$)?',
    choices: [
      '$7\\pi\\,\\text{cm}$',
      '$14\\pi\\,\\text{cm}$',
      '$49\\pi\\,\\text{cm}$',
      '$\\pi^2\\,\\text{cm}$',
    ],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Circumference of a circle',
  },
  {
    id: 'jc-gt-pyth-m-1',
    stage: 'junior_cycle',
    strand: 'geometry_trig',
    learningOutcome: 'JC.GT.O.8: Apply the Pythagorean theorem to find a missing side',
    b: 0,
    text: 'A right-angled triangle has legs of length $5$ and $12$. What is the length of the hypotenuse?',
    choices: ['$13$', '$17$', '$\\sqrt{17}$', '$\\sqrt{119}$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Pythagorean theorem',
  },
  {
    id: 'jc-gt-area-m-1',
    stage: 'junior_cycle',
    strand: 'geometry_trig',
    learningOutcome: 'JC.GT.O.9: Calculate the area of a triangle',
    b: 0,
    text: 'A triangle has base $10\\,\\text{cm}$ and height $6\\,\\text{cm}$. What is its area?',
    choices: [
      '$16\\,\\text{cm}^2$',
      '$60\\,\\text{cm}^2$',
      '$30\\,\\text{cm}^2$',
      '$32\\,\\text{cm}^2$',
    ],
    correctIndex: 2,
    source: 'anchor',
    khanAcademyRef: 'KA: Area of a triangle',
  },
  {
    id: 'jc-gt-trig-h-1',
    stage: 'junior_cycle',
    strand: 'geometry_trig',
    learningOutcome: 'JC.GT.H.7: Apply the cosine ratio in right-angled triangles',
    b: 1,
    text: 'In a right-angled triangle the hypotenuse is $10$ and one acute angle is $60^\\circ$. What is the length of the side adjacent to the $60^\\circ$ angle?',
    choices: ['$5$', '$5\\sqrt{3}$', '$10\\sqrt{3}$', '$\\frac{1}{2}$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Trigonometric ratios in right triangles',
  },
  {
    id: 'jc-gt-vol-h-1',
    stage: 'junior_cycle',
    strand: 'geometry_trig',
    learningOutcome: 'JC.GT.H.8: Calculate the volume of a cylinder',
    b: 1,
    text: 'A cylinder has radius $3\\,\\text{cm}$ and height $5\\,\\text{cm}$. What is its volume in terms of $\\pi$?',
    choices: [
      '$15\\pi\\,\\text{cm}^3$',
      '$30\\pi\\,\\text{cm}^3$',
      '$45\\pi\\,\\text{cm}^3$',
      '$9\\pi\\,\\text{cm}^3$',
    ],
    correctIndex: 2,
    source: 'anchor',
    khanAcademyRef: 'KA: Volume of cylinders',
  },
  {
    id: 'jc-gt-coord-h-1',
    stage: 'junior_cycle',
    strand: 'geometry_trig',
    learningOutcome: 'JC.GT.H.9: Find the midpoint of a line segment',
    b: 2,
    text: 'Find the midpoint of the segment joining $A(-2, 4)$ and $B(6, -2)$.',
    choices: ['$(2, 1)$', '$(4, 2)$', '$(2, 2)$', '$(8, 6)$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Midpoint formula',
  },
  // -- functions: easy/medium/hard expansion --
  {
    id: 'jc-fn-eval-e-1',
    stage: 'junior_cycle',
    strand: 'functions',
    learningOutcome: 'JC.FN.U.7: Evaluate a linear function at zero',
    b: -2,
    text: 'If $f(x) = 5x - 4$, what is $f(0)$?',
    choices: ['$0$', '$-4$', '$4$', '$5$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Evaluating functions',
  },
  {
    id: 'jc-fn-eval-e-2',
    stage: 'junior_cycle',
    strand: 'functions',
    learningOutcome: 'JC.FN.U.8: Evaluate a linear function at a positive integer',
    b: -2,
    text: 'If $g(x) = x + 6$, what is $g(4)$?',
    choices: ['$6$', '$10$', '$24$', '$2$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Evaluating functions',
  },
  {
    id: 'jc-fn-slo-e-1',
    stage: 'junior_cycle',
    strand: 'functions',
    learningOutcome: 'JC.FN.U.9: Identify the slope of a line in slope-intercept form',
    b: -1,
    text: 'What is the slope of the line $y = -3x + 2$?',
    choices: ['$2$', '$-3$', '$3$', '$-2$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Slope-intercept form',
  },
  {
    id: 'jc-fn-int-m-1',
    stage: 'junior_cycle',
    strand: 'functions',
    learningOutcome: 'JC.FN.O.7: Identify the y-intercept of a linear function',
    b: -1,
    text: 'What is the y-intercept of the line $y = 6x - 11$?',
    choices: ['$6$', '$-11$', '$11$', '$-6$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Y-intercept',
  },
  {
    id: 'jc-fn-eval-m-1',
    stage: 'junior_cycle',
    strand: 'functions',
    learningOutcome: 'JC.FN.O.8: Evaluate a quadratic function at a negative integer',
    b: 0,
    text: 'If $f(x) = x^2 + 1$, what is $f(-2)$?',
    choices: ['$-3$', '$5$', '$-5$', '$3$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Evaluating functions',
  },
  {
    id: 'jc-fn-slo-m-1',
    stage: 'junior_cycle',
    strand: 'functions',
    learningOutcome: 'JC.FN.O.9: Calculate slope from two points',
    b: 0,
    text: 'What is the slope of the line through $(1, 2)$ and $(4, 11)$?',
    choices: ['$3$', '$\\frac{1}{3}$', '$9$', '$-3$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Slope from two points',
  },
  {
    id: 'jc-fn-roo-h-1',
    stage: 'junior_cycle',
    strand: 'functions',
    learningOutcome: 'JC.FN.H.7: Find the roots of a factorised quadratic function',
    b: 1,
    text: 'What are the roots of $f(x) = (x - 2)(x + 5)$?',
    choices: [
      '$x = 2, x = -5$',
      '$x = -2, x = 5$',
      '$x = 2, x = 5$',
      '$x = -2, x = -5$',
    ],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Zeros of quadratic functions',
  },
  {
    id: 'jc-fn-vert-h-1',
    stage: 'junior_cycle',
    strand: 'functions',
    learningOutcome: 'JC.FN.H.8: Identify the vertex of a quadratic in vertex form',
    b: 1,
    text: 'What is the vertex of the parabola $y = (x + 1)^2 - 4$?',
    choices: ['$(-1, -4)$', '$(1, -4)$', '$(-1, 4)$', '$(1, 4)$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Vertex form of a quadratic',
  },
  {
    id: 'jc-fn-trans-h-1',
    stage: 'junior_cycle',
    strand: 'functions',
    learningOutcome: 'JC.FN.H.9: Apply translations to a function',
    b: 2,
    text: 'The graph of $y = x^2$ is translated $3$ units to the right and $2$ units down. Which equation describes the new graph?',
    choices: [
      '$y = (x + 3)^2 - 2$',
      '$y = (x - 3)^2 - 2$',
      '$y = (x - 3)^2 + 2$',
      '$y = (x + 3)^2 + 2$',
    ],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Transformations of functions',
  },
  // -- statistics_prob: easy/medium/hard expansion --
  {
    id: 'jc-sp-mean-e-1',
    stage: 'junior_cycle',
    strand: 'statistics_prob',
    learningOutcome: 'JC.SP.U.7: Calculate the mean of a small data set',
    b: -2,
    text: 'Find the mean of the data: $2, 4, 6, 8$.',
    choices: ['$4$', '$5$', '$6$', '$20$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Mean, median, mode',
  },
  {
    id: 'jc-sp-mode-e-1',
    stage: 'junior_cycle',
    strand: 'statistics_prob',
    learningOutcome: 'JC.SP.U.8: Identify the mode of a data set',
    b: -2,
    text: 'What is the mode of the data: $1, 2, 2, 3, 4, 5, 2$?',
    choices: ['$1$', '$2$', '$3$', '$5$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Mean, median, mode',
  },
  {
    id: 'jc-sp-med-e-1',
    stage: 'junior_cycle',
    strand: 'statistics_prob',
    learningOutcome: 'JC.SP.U.9: Identify the median of an even-sized data set',
    b: -1,
    text: 'What is the median of the data: $2, 5, 7, 9, 12, 16$?',
    choices: ['$7$', '$9$', '$8$', '$8.5$'],
    correctIndex: 2,
    source: 'anchor',
    khanAcademyRef: 'KA: Mean, median, mode',
  },
  {
    id: 'jc-sp-rng-m-1',
    stage: 'junior_cycle',
    strand: 'statistics_prob',
    learningOutcome: 'JC.SP.O.7: Calculate the range of a data set',
    b: -1,
    text: 'Find the range of the data: $12, 5, 8, 20, 3$.',
    choices: ['$5$', '$17$', '$15$', '$20$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Range of a data set',
  },
  {
    id: 'jc-sp-prob-m-1',
    stage: 'junior_cycle',
    strand: 'statistics_prob',
    learningOutcome: 'JC.SP.O.8: Calculate single-event probability',
    b: 0,
    text: 'A bag has $3$ red, $5$ blue and $2$ green marbles. What is the probability of picking a blue marble at random?',
    choices: ['$\\frac{1}{5}$', '$\\frac{1}{2}$', '$\\frac{3}{10}$', '$\\frac{1}{3}$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Basic probability',
  },
  {
    id: 'jc-sp-prob-m-2',
    stage: 'junior_cycle',
    strand: 'statistics_prob',
    learningOutcome: 'JC.SP.O.9: Calculate complementary event probability',
    b: 0,
    text: 'The probability that it rains tomorrow is $\\frac{2}{5}$. What is the probability that it does not rain tomorrow?',
    choices: ['$\\frac{2}{5}$', '$\\frac{3}{5}$', '$\\frac{5}{2}$', '$\\frac{1}{5}$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Complementary events',
  },
  {
    id: 'jc-sp-iqr-h-1',
    stage: 'junior_cycle',
    strand: 'statistics_prob',
    learningOutcome: 'JC.SP.H.7: Calculate the interquartile range of a data set',
    b: 1,
    text: 'Find the interquartile range of the data: $2, 4, 6, 8, 10, 12, 14, 16$.',
    choices: ['$8$', '$14$', '$7$', '$6$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Interquartile range',
  },
  {
    id: 'jc-sp-prob-h-1',
    stage: 'junior_cycle',
    strand: 'statistics_prob',
    learningOutcome: 'JC.SP.H.8: Calculate combined probability of independent events',
    b: 1,
    text: 'Two fair coins are tossed. What is the probability of getting two heads?',
    choices: ['$\\frac{1}{2}$', '$\\frac{1}{4}$', '$\\frac{1}{3}$', '$\\frac{3}{4}$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Probability with combined events',
  },
  {
    id: 'jc-sp-prob-h-2',
    stage: 'junior_cycle',
    strand: 'statistics_prob',
    learningOutcome: 'JC.SP.H.9: Calculate combined probability with a die and coin',
    b: 2,
    text: 'A fair coin is tossed and a fair six-sided die is rolled. What is the probability of getting heads and a number greater than $4$?',
    choices: ['$\\frac{1}{6}$', '$\\frac{1}{4}$', '$\\frac{1}{3}$', '$\\frac{1}{12}$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Probability with combined events',
  },
  // ============================================================
  // PRIMARY items (b ~ -3.0 to -1.0)
  // ============================================================
  // -- primary: number --
  {
    id: 'pr-nu-add-1',
    stage: 'primary',
    strand: 'number',
    learningOutcome: 'PR.NU.1: Add two two-digit numbers',
    b: -3,
    text: 'What is $24 + 35$?',
    choices: ['$49$', '$59$', '$69$', '$58$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Two-digit addition',
  },
  {
    id: 'pr-nu-sub-1',
    stage: 'primary',
    strand: 'number',
    learningOutcome: 'PR.NU.2: Subtract two two-digit numbers',
    b: -3,
    text: 'What is $72 - 28$?',
    choices: ['$46$', '$54$', '$44$', '$48$'],
    correctIndex: 2,
    source: 'anchor',
    khanAcademyRef: 'KA: Two-digit subtraction',
  },
  {
    id: 'pr-nu-mul-1',
    stage: 'primary',
    strand: 'number',
    learningOutcome: 'PR.NU.3: Recall basic multiplication facts',
    b: -3,
    text: 'What is $6 \\times 9$?',
    choices: ['$48$', '$56$', '$54$', '$63$'],
    correctIndex: 2,
    source: 'anchor',
    khanAcademyRef: 'KA: Multiplication facts',
  },
  {
    id: 'pr-nu-div-1',
    stage: 'primary',
    strand: 'number',
    learningOutcome: 'PR.NU.4: Divide using basic division facts',
    b: -2.5,
    text: 'What is $48 \\div 6$?',
    choices: ['$6$', '$7$', '$8$', '$9$'],
    correctIndex: 2,
    source: 'anchor',
    khanAcademyRef: 'KA: Division facts',
  },
  {
    id: 'pr-nu-frac-1',
    stage: 'primary',
    strand: 'number',
    learningOutcome: 'PR.NU.5: Identify simple fractions',
    b: -2.5,
    text: 'A pizza is cut into $8$ equal slices. You eat $2$ slices. What fraction of the pizza did you eat?',
    choices: ['$\\frac{1}{4}$', '$\\frac{1}{2}$', '$\\frac{2}{6}$', '$\\frac{1}{8}$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Fractions intro',
  },
  {
    id: 'pr-nu-dec-1',
    stage: 'primary',
    strand: 'number',
    learningOutcome: 'PR.NU.6: Add decimals to one place',
    b: -2,
    text: 'Evaluate $1.4 + 2.7$.',
    choices: ['$3.1$', '$4.1$', '$3.11$', '$4.11$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Decimal addition',
  },
  {
    id: 'pr-nu-money-1',
    stage: 'primary',
    strand: 'number',
    learningOutcome: 'PR.NU.7: Calculate change from a sum of money',
    b: -2,
    text: 'A book costs \u20ac6.50. You pay with a \u20ac10 note. How much change do you get?',
    choices: ['\u20ac3.50', '\u20ac4.50', '\u20ac3.00', '\u20ac4.00'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Money',
  },
  {
    id: 'pr-nu-round-1',
    stage: 'primary',
    strand: 'number',
    learningOutcome: 'PR.NU.8: Round whole numbers to the nearest ten',
    b: -2,
    text: 'Round $47$ to the nearest $10$.',
    choices: ['$40$', '$50$', '$45$', '$47$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Rounding',
  },
  // -- primary: algebra (very simple — fill in the blank, patterns) --
  {
    id: 'pr-al-blank-1',
    stage: 'primary',
    strand: 'algebra',
    learningOutcome: 'PR.AL.1: Solve a missing-number equation',
    b: -2.5,
    text: 'What number goes in the box: $\\square + 7 = 12$?',
    choices: ['$3$', '$4$', '$5$', '$6$'],
    correctIndex: 2,
    source: 'anchor',
    khanAcademyRef: 'KA: Missing numbers',
  },
  {
    id: 'pr-al-pat-1',
    stage: 'primary',
    strand: 'algebra',
    learningOutcome: 'PR.AL.2: Continue a number pattern',
    b: -2,
    text: 'What is the next number in the pattern: $2, 5, 8, 11, \\dots$?',
    choices: ['$13$', '$14$', '$15$', '$12$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Number patterns',
  },
  {
    id: 'pr-al-blank-2',
    stage: 'primary',
    strand: 'algebra',
    learningOutcome: 'PR.AL.3: Solve a missing-number multiplication',
    b: -2,
    text: 'What number goes in the box: $4 \\times \\square = 28$?',
    choices: ['$5$', '$6$', '$7$', '$8$'],
    correctIndex: 2,
    source: 'anchor',
    khanAcademyRef: 'KA: Missing numbers',
  },
  // -- primary: geometry/trig --
  {
    id: 'pr-gt-shape-1',
    stage: 'primary',
    strand: 'geometry_trig',
    learningOutcome: 'PR.GT.1: Identify 2D shapes by side count',
    b: -3,
    text: 'How many sides does a hexagon have?',
    choices: ['$5$', '$6$', '$7$', '$8$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: 2D shapes',
  },
  {
    id: 'pr-gt-area-1',
    stage: 'primary',
    strand: 'geometry_trig',
    learningOutcome: 'PR.GT.2: Calculate area of a square',
    b: -2,
    text: 'A square has side length $5\\,\\text{cm}$. What is its area?',
    choices: ['$10\\,\\text{cm}^2$', '$20\\,\\text{cm}^2$', '$25\\,\\text{cm}^2$', '$15\\,\\text{cm}^2$'],
    correctIndex: 2,
    source: 'anchor',
    khanAcademyRef: 'KA: Area of squares',
  },
  {
    id: 'pr-gt-per-1',
    stage: 'primary',
    strand: 'geometry_trig',
    learningOutcome: 'PR.GT.3: Calculate perimeter of a square',
    b: -2.5,
    text: 'A square has side length $7\\,\\text{cm}$. What is its perimeter?',
    choices: ['$14\\,\\text{cm}$', '$28\\,\\text{cm}$', '$21\\,\\text{cm}$', '$49\\,\\text{cm}$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Perimeter',
  },
  {
    id: 'pr-gt-time-1',
    stage: 'primary',
    strand: 'geometry_trig',
    learningOutcome: 'PR.GT.4: Calculate elapsed time',
    b: -2,
    text: 'A film starts at $7{:}30$ and ends at $9{:}15$. How long is the film?',
    choices: ['$1$ hour $15$ minutes', '$1$ hour $45$ minutes', '$2$ hours $15$ minutes', '$2$ hours $45$ minutes'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Telling time',
  },
  // -- primary: functions (very basic input/output tables) --
  {
    id: 'pr-fn-tab-1',
    stage: 'primary',
    strand: 'functions',
    learningOutcome: 'PR.FN.1: Read input/output from a function rule',
    b: -2,
    text: 'A rule says "double the input and add $1$". If the input is $4$, what is the output?',
    choices: ['$5$', '$8$', '$9$', '$10$'],
    correctIndex: 2,
    source: 'anchor',
    khanAcademyRef: 'KA: Input-output tables',
  },
  {
    id: 'pr-fn-tab-2',
    stage: 'primary',
    strand: 'functions',
    learningOutcome: 'PR.FN.2: Identify a function rule from values',
    b: -1.5,
    text: 'A function maps $1 \\to 4$, $2 \\to 5$, $3 \\to 6$. What is the rule?',
    choices: ['Multiply by $4$', 'Add $3$', 'Multiply by $2$', 'Subtract $3$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Function rules',
  },
  // -- primary: statistics_prob --
  {
    id: 'pr-sp-tally-1',
    stage: 'primary',
    strand: 'statistics_prob',
    learningOutcome: 'PR.SP.1: Read information from a tally chart',
    b: -2,
    text: 'A class voted for favourite fruit: apple $7$, banana $5$, orange $3$. How many students voted in total?',
    choices: ['$12$', '$15$', '$10$', '$18$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Reading tables',
  },
  {
    id: 'pr-sp-mean-1',
    stage: 'primary',
    strand: 'statistics_prob',
    learningOutcome: 'PR.SP.2: Calculate the mean of a small data set',
    b: -1.5,
    text: 'Find the mean of the data: $3, 5, 7$.',
    choices: ['$3$', '$5$', '$7$', '$15$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Mean',
  },
  {
    id: 'pr-sp-prob-1',
    stage: 'primary',
    strand: 'statistics_prob',
    learningOutcome: 'PR.SP.3: Describe likelihood of simple events',
    b: -2,
    text: 'A bag has $5$ red counters and $1$ blue counter. Picking at random, which colour is more likely?',
    choices: ['Red', 'Blue', 'Equally likely', 'Cannot tell'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Probability intro',
  },
  // ============================================================
  // LEAVING CERT ORDINARY items (b ~ 0.5 to 1.5)
  // ============================================================
  // -- LC OL: number --
  {
    id: 'lc-nu-fin-o-1',
    stage: 'leaving_cert',
    strand: 'number',
    learningOutcome: 'LC.NU.O.1: Calculate compound interest',
    b: 1,
    text: '\u20ac1{,}000 is invested at $5\\%$ compound interest per annum for $2$ years. What is the final amount (to the nearest \u20ac)?',
    choices: ['\u20ac1{,}100', '\u20ac1{,}102.50', '\u20ac1{,}105', '\u20ac1{,}050'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Compound interest',
  },
  {
    id: 'lc-nu-fin-o-2',
    stage: 'leaving_cert',
    strand: 'number',
    learningOutcome: 'LC.NU.O.2: Apply percentage depreciation',
    b: 1,
    text: 'A car worth \u20ac20{,}000 depreciates at $10\\%$ per year. What is its value after $2$ years (to the nearest \u20ac)?',
    choices: ['\u20ac16{,}000', '\u20ac16{,}200', '\u20ac18{,}000', '\u20ac16{,}100'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Depreciation',
  },
  {
    id: 'lc-nu-pct-o-1',
    stage: 'leaving_cert',
    strand: 'number',
    learningOutcome: 'LC.NU.O.3: Reverse percentage problems',
    b: 0.8,
    text: 'After a $20\\%$ discount, an item costs \u20ac160. What was its original price?',
    choices: ['\u20ac180', '\u20ac192', '\u20ac200', '\u20ac128'],
    correctIndex: 2,
    source: 'anchor',
    khanAcademyRef: 'KA: Reverse percentages',
  },
  // -- LC OL: algebra --
  {
    id: 'lc-al-log-o-1',
    stage: 'leaving_cert',
    strand: 'algebra',
    learningOutcome: 'LC.AL.O.1: Evaluate logarithms in base 10',
    b: 1,
    text: 'Evaluate $\\log_{10}(1000)$.',
    choices: ['$1$', '$2$', '$3$', '$10$'],
    correctIndex: 2,
    source: 'anchor',
    khanAcademyRef: 'KA: Logarithms',
  },
  {
    id: 'lc-al-exp-o-1',
    stage: 'leaving_cert',
    strand: 'algebra',
    learningOutcome: 'LC.AL.O.2: Solve simple exponential equations',
    b: 1.2,
    text: 'Solve $2^{x} = 32$ for $x$.',
    choices: ['$4$', '$5$', '$6$', '$\\log_{2}(32)/\\log_{2}(10)$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Exponential equations',
  },
  {
    id: 'lc-al-poly-o-1',
    stage: 'leaving_cert',
    strand: 'algebra',
    learningOutcome: 'LC.AL.O.3: Perform polynomial long division',
    b: 1.3,
    text: 'Divide $x^2 + 5x + 6$ by $x + 2$.',
    choices: ['$x + 3$', '$x + 2$', '$x + 4$', '$x - 3$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Polynomial division',
  },
  {
    id: 'lc-al-ineq-o-1',
    stage: 'leaving_cert',
    strand: 'algebra',
    learningOutcome: 'LC.AL.O.4: Solve linear inequalities',
    b: 0.8,
    text: 'Solve for $x$: $3x - 4 < 8$.',
    choices: ['$x < 4$', '$x > 4$', '$x \\le 4$', '$x < \\frac{4}{3}$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Linear inequalities',
  },
  // -- LC OL: geometry/trig --
  {
    id: 'lc-gt-line-o-1',
    stage: 'leaving_cert',
    strand: 'geometry_trig',
    learningOutcome: 'LC.GT.O.1: Find the slope of a line through two points',
    b: 0.8,
    text: 'Find the slope of the line through $(2, 3)$ and $(5, 12)$.',
    choices: ['$3$', '$\\frac{1}{3}$', '$-3$', '$9$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Slope from two points',
  },
  {
    id: 'lc-gt-line-o-2',
    stage: 'leaving_cert',
    strand: 'geometry_trig',
    learningOutcome: 'LC.GT.O.2: Write equation of a line in slope-intercept form',
    b: 1,
    text: 'Find the equation of the line with slope $2$ passing through $(1, 5)$.',
    choices: ['$y = 2x + 3$', '$y = 2x + 5$', '$y = 2x + 7$', '$y = 2x - 3$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Point-slope form',
  },
  {
    id: 'lc-gt-circle-o-1',
    stage: 'leaving_cert',
    strand: 'geometry_trig',
    learningOutcome: 'LC.GT.O.3: Identify centre and radius of a circle',
    b: 1.2,
    text: 'Find the centre and radius of the circle $(x - 3)^2 + (y + 2)^2 = 25$.',
    choices: [
      'Centre $(3, -2)$, radius $5$',
      'Centre $(-3, 2)$, radius $5$',
      'Centre $(3, -2)$, radius $25$',
      'Centre $(-3, 2)$, radius $25$',
    ],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Equation of a circle',
  },
  {
    id: 'lc-gt-trig-o-1',
    stage: 'leaving_cert',
    strand: 'geometry_trig',
    learningOutcome: 'LC.GT.O.4: Apply the cosine rule',
    b: 1.3,
    text: 'In a triangle with sides $a = 5$, $b = 7$ and the angle between them $C = 60^\\circ$, find $c^2$ using the cosine rule.',
    choices: ['$39$', '$74$', '$109$', '$35$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Law of cosines',
  },
  // -- LC OL: functions --
  {
    id: 'lc-fn-deriv-o-1',
    stage: 'leaving_cert',
    strand: 'functions',
    learningOutcome: 'LC.FN.O.1: Differentiate a polynomial',
    b: 1,
    text: 'Find $\\frac{d}{dx}(3x^2 + 4x - 7)$.',
    choices: ['$6x + 4$', '$3x + 4$', '$6x - 7$', '$6x^2 + 4$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Power rule',
  },
  {
    id: 'lc-fn-deriv-o-2',
    stage: 'leaving_cert',
    strand: 'functions',
    learningOutcome: 'LC.FN.O.2: Evaluate a derivative at a point',
    b: 1.2,
    text: 'If $f(x) = x^3 - 2x$, find $f\\,\u2019(2)$.',
    choices: ['$6$', '$10$', '$12$', '$8$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Power rule',
  },
  {
    id: 'lc-fn-comp-o-1',
    stage: 'leaving_cert',
    strand: 'functions',
    learningOutcome: 'LC.FN.O.3: Evaluate a composition of functions',
    b: 1,
    text: 'If $f(x) = 2x + 1$ and $g(x) = x^2$, find $f(g(3))$.',
    choices: ['$19$', '$49$', '$10$', '$13$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Composing functions',
  },
  {
    id: 'lc-fn-inv-o-1',
    stage: 'leaving_cert',
    strand: 'functions',
    learningOutcome: 'LC.FN.O.4: Find the inverse of a linear function',
    b: 1,
    text: 'Find the inverse of $f(x) = 3x - 6$.',
    choices: [
      '$f^{-1}(x) = \\frac{x + 6}{3}$',
      '$f^{-1}(x) = \\frac{x - 6}{3}$',
      '$f^{-1}(x) = 3x + 6$',
      '$f^{-1}(x) = \\frac{1}{3x - 6}$',
    ],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Inverse functions',
  },
  // -- LC OL: statistics_prob --
  {
    id: 'lc-sp-stat-o-1',
    stage: 'leaving_cert',
    strand: 'statistics_prob',
    learningOutcome: 'LC.SP.O.1: Calculate standard deviation of a small data set',
    b: 1.3,
    text: 'Find the standard deviation of the data $2, 4, 4, 4, 5, 5, 7, 9$ (mean $= 5$).',
    choices: ['$2$', '$3$', '$\\sqrt{4}$', '$4$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Standard deviation',
  },
  {
    id: 'lc-sp-prob-o-1',
    stage: 'leaving_cert',
    strand: 'statistics_prob',
    learningOutcome: 'LC.SP.O.2: Apply the addition rule for mutually exclusive events',
    b: 0.8,
    text: 'A card is drawn from a standard deck. What is the probability it is a King or a Queen?',
    choices: ['$\\frac{1}{13}$', '$\\frac{2}{13}$', '$\\frac{1}{26}$', '$\\frac{4}{13}$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Addition rule',
  },
  {
    id: 'lc-sp-tree-o-1',
    stage: 'leaving_cert',
    strand: 'statistics_prob',
    learningOutcome: 'LC.SP.O.3: Apply tree diagrams to compute probabilities',
    b: 1.2,
    text: 'A bag has $4$ red and $6$ blue balls. Two balls are drawn without replacement. What is the probability both are red?',
    choices: ['$\\frac{2}{15}$', '$\\frac{4}{25}$', '$\\frac{16}{100}$', '$\\frac{1}{5}$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Conditional probability',
  },
  // ============================================================
  // LEAVING CERT HIGHER items (b ~ 1.0 to 3.0)
  // ============================================================
  // -- LC HL: number (complex numbers, financial) --
  {
    id: 'lc-nu-cplx-h-1',
    stage: 'leaving_cert',
    strand: 'number',
    learningOutcome: 'LC.NU.H.1: Add and subtract complex numbers',
    b: 1.5,
    text: 'Evaluate $(3 + 2i) + (1 - 5i)$.',
    choices: ['$4 - 3i$', '$4 + 3i$', '$2 - 3i$', '$4 - 7i$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Complex numbers',
  },
  {
    id: 'lc-nu-cplx-h-2',
    stage: 'leaving_cert',
    strand: 'number',
    learningOutcome: 'LC.NU.H.2: Multiply complex numbers',
    b: 2,
    text: 'Evaluate $(2 + i)(3 - 4i)$.',
    choices: ['$6 - 4i^2 + i$', '$10 - 5i$', '$2 - 5i$', '$6 - 5i$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Multiplying complex numbers',
  },
  {
    id: 'lc-nu-cplx-h-3',
    stage: 'leaving_cert',
    strand: 'number',
    learningOutcome: 'LC.NU.H.3: Find the modulus of a complex number',
    b: 2,
    text: 'Find $|3 - 4i|$.',
    choices: ['$5$', '$7$', '$25$', '$\\sqrt{7}$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Modulus of complex numbers',
  },
  {
    id: 'lc-nu-cplx-h-4',
    stage: 'leaving_cert',
    strand: 'number',
    learningOutcome: 'LC.NU.H.4: Divide complex numbers using the conjugate',
    b: 2.5,
    text: 'Express $\\frac{1 + i}{1 - i}$ in the form $a + bi$.',
    choices: ['$i$', '$1$', '$-i$', '$1 + i$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Dividing complex numbers',
  },
  {
    id: 'lc-nu-fin-h-1',
    stage: 'leaving_cert',
    strand: 'number',
    learningOutcome: 'LC.NU.H.5: Calculate AER from a monthly rate',
    b: 2,
    text: 'A savings account pays $0.5\\%$ per month compounded monthly. What is the AER (to the nearest $0.1\\%$)?',
    choices: ['$6.0\\%$', '$6.2\\%$', '$5.0\\%$', '$6.17\\%$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Compound interest',
  },
  {
    id: 'lc-nu-fin-h-2',
    stage: 'leaving_cert',
    strand: 'number',
    learningOutcome: 'LC.NU.H.6: Mortgage amortisation present value',
    b: 2.5,
    text: 'A mortgage repayment formula gives $A = P \\cdot \\frac{r(1+r)^n}{(1+r)^n - 1}$. If $P = 100{,}000$, monthly rate $r = 0.005$ and $n = 240$ months, what does $A$ represent?',
    choices: [
      'The total interest paid',
      'The monthly repayment',
      'The remaining balance after $n$ months',
      'The annual repayment',
    ],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Mortgages',
  },
  // -- LC HL: algebra (induction, logs, inequalities) --
  {
    id: 'lc-al-log-h-1',
    stage: 'leaving_cert',
    strand: 'algebra',
    learningOutcome: 'LC.AL.H.1: Apply log laws to combine logarithms',
    b: 1.5,
    text: 'Express $\\log_{10}(8) + \\log_{10}(125)$ as a single value.',
    choices: ['$3$', '$\\log_{10}(133)$', '$\\log_{10}(1000)$', '$\\log_{10}(8 \\cdot 125)$ only'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Properties of logarithms',
  },
  {
    id: 'lc-al-log-h-2',
    stage: 'leaving_cert',
    strand: 'algebra',
    learningOutcome: 'LC.AL.H.2: Solve logarithmic equations',
    b: 2,
    text: 'Solve for $x$: $\\log_{2}(x) + \\log_{2}(x - 2) = 3$.',
    choices: ['$x = 4$', '$x = 2$', '$x = -2$', '$x = 4$ or $x = -2$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Solving logarithmic equations',
  },
  {
    id: 'lc-al-ind-h-1',
    stage: 'leaving_cert',
    strand: 'algebra',
    learningOutcome: 'LC.AL.H.3: Identify the inductive step in a proof by induction',
    b: 2.5,
    text: 'In an induction proof of "$1 + 2 + \\dots + n = \\frac{n(n+1)}{2}$ for all $n \\ge 1$", what must the inductive step show?',
    choices: [
      'The formula holds for $n = 1$',
      'If the formula holds for $n = k$, then it holds for $n = k + 1$',
      'The formula holds for $n = 0$',
      'The formula holds for some specific large $n$',
    ],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Mathematical induction',
  },
  {
    id: 'lc-al-ind-h-2',
    stage: 'leaving_cert',
    strand: 'algebra',
    learningOutcome: 'LC.AL.H.4: Apply the induction hypothesis to deduce the next case',
    b: 2.8,
    text: 'In a proof by induction of $\\sum_{r=1}^{n} r = \\frac{n(n+1)}{2}$, assume $\\sum_{r=1}^{k} r = \\frac{k(k+1)}{2}$. Adding $(k+1)$ to both sides gives:',
    choices: [
      '$\\frac{k(k+1)}{2} + (k+1) = \\frac{(k+1)(k+2)}{2}$',
      '$\\frac{k(k+1)}{2} + (k+1) = \\frac{k(k+2)}{2}$',
      '$\\frac{k(k+1)}{2} + (k+1) = \\frac{(k+1)^2}{2}$',
      '$\\frac{k(k+1)}{2} + (k+1) = \\frac{k^2 + k + 1}{2}$',
    ],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Mathematical induction',
  },
  {
    id: 'lc-al-ineq-h-1',
    stage: 'leaving_cert',
    strand: 'algebra',
    learningOutcome: 'LC.AL.H.5: Solve quadratic inequalities',
    b: 2,
    text: 'Solve the inequality $x^2 - x - 6 < 0$.',
    choices: [
      '$-2 < x < 3$',
      '$x < -2$ or $x > 3$',
      '$2 < x < 3$',
      '$-3 < x < 2$',
    ],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Quadratic inequalities',
  },
  {
    id: 'lc-al-mod-h-1',
    stage: 'leaving_cert',
    strand: 'algebra',
    learningOutcome: 'LC.AL.H.6: Solve modulus equations',
    b: 2,
    text: 'Solve $|2x - 3| = 7$.',
    choices: ['$x = 5$ or $x = -2$', '$x = 5$ only', '$x = 2$ or $x = -5$', '$x = -5$ or $x = 2$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Absolute value equations',
  },
  // -- LC HL: geometry/trig (vectors, 3D, identities) --
  {
    id: 'lc-gt-vec-h-1',
    stage: 'leaving_cert',
    strand: 'geometry_trig',
    learningOutcome: 'LC.GT.H.1: Compute the dot product of two vectors',
    b: 1.8,
    text: 'Find $\\vec{a} \\cdot \\vec{b}$ where $\\vec{a} = (2, 3)$ and $\\vec{b} = (4, -1)$.',
    choices: ['$5$', '$11$', '$8$', '$-3$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Dot product',
  },
  {
    id: 'lc-gt-vec-h-2',
    stage: 'leaving_cert',
    strand: 'geometry_trig',
    learningOutcome: 'LC.GT.H.2: Find the magnitude of a vector',
    b: 1.5,
    text: 'Find $|\\vec{v}|$ where $\\vec{v} = (3, 4)$.',
    choices: ['$5$', '$7$', '$\\sqrt{7}$', '$25$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Vector magnitude',
  },
  {
    id: 'lc-gt-vec-h-3',
    stage: 'leaving_cert',
    strand: 'geometry_trig',
    learningOutcome: 'LC.GT.H.3: Determine when two vectors are perpendicular',
    b: 2,
    text: 'For which value of $k$ are $\\vec{a} = (2, k)$ and $\\vec{b} = (3, 6)$ perpendicular?',
    choices: ['$k = -1$', '$k = 1$', '$k = -4$', '$k = 4$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Perpendicular vectors',
  },
  {
    id: 'lc-gt-3d-h-1',
    stage: 'leaving_cert',
    strand: 'geometry_trig',
    learningOutcome: 'LC.GT.H.4: Find distance between two points in 3D',
    b: 2.2,
    text: 'Find the distance between $A(1, 2, 3)$ and $B(4, 6, 3)$.',
    choices: ['$5$', '$7$', '$\\sqrt{34}$', '$\\sqrt{26}$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Distance in 3D',
  },
  {
    id: 'lc-gt-id-h-1',
    stage: 'leaving_cert',
    strand: 'geometry_trig',
    learningOutcome: 'LC.GT.H.5: Apply the Pythagorean trig identity',
    b: 1.8,
    text: 'If $\\sin\\theta = \\frac{3}{5}$ and $\\theta$ is acute, find $\\cos\\theta$.',
    choices: ['$\\frac{4}{5}$', '$\\frac{3}{4}$', '$\\frac{5}{4}$', '$-\\frac{4}{5}$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Pythagorean identity',
  },
  {
    id: 'lc-gt-id-h-2',
    stage: 'leaving_cert',
    strand: 'geometry_trig',
    learningOutcome: 'LC.GT.H.6: Apply the double angle formula for sine',
    b: 2.2,
    text: 'If $\\sin\\theta = \\frac{1}{2}$ and $\\cos\\theta = \\frac{\\sqrt{3}}{2}$, find $\\sin(2\\theta)$.',
    choices: ['$\\frac{\\sqrt{3}}{2}$', '$\\frac{1}{2}$', '$1$', '$\\frac{\\sqrt{3}}{4}$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Double angle formulas',
  },
  {
    id: 'lc-gt-line-h-1',
    stage: 'leaving_cert',
    strand: 'geometry_trig',
    learningOutcome: 'LC.GT.H.7: Find the perpendicular distance from a point to a line',
    b: 2.5,
    text: 'Find the perpendicular distance from $(3, 4)$ to the line $3x + 4y - 5 = 0$.',
    choices: ['$4$', '$5$', '$3$', '$\\frac{20}{5}$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Distance from point to line',
  },
  {
    id: 'lc-gt-circle-h-1',
    stage: 'leaving_cert',
    strand: 'geometry_trig',
    learningOutcome: 'LC.GT.H.8: Determine the equation of a tangent to a circle',
    b: 2.5,
    text: 'The line $y = 3x + c$ is tangent to the circle $x^2 + y^2 = 10$. Find a possible value of $c$.',
    choices: ['$c = 10$', '$c = \\sqrt{100}$', '$c = \\pm 10$', '$c = 5$'],
    correctIndex: 2,
    source: 'anchor',
    khanAcademyRef: 'KA: Tangent to a circle',
  },
  // -- LC HL: functions (calculus) --
  {
    id: 'lc-fn-deriv-h-1',
    stage: 'leaving_cert',
    strand: 'functions',
    learningOutcome: 'LC.FN.H.1: Apply the product rule',
    b: 1.8,
    text: 'Differentiate $f(x) = x^2 \\sin(x)$.',
    choices: [
      '$2x \\sin(x) + x^2 \\cos(x)$',
      '$2x \\cos(x)$',
      '$x^2 \\cos(x)$',
      '$2x \\sin(x) - x^2 \\cos(x)$',
    ],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Product rule',
  },
  {
    id: 'lc-fn-deriv-h-2',
    stage: 'leaving_cert',
    strand: 'functions',
    learningOutcome: 'LC.FN.H.2: Apply the quotient rule',
    b: 2,
    text: 'Differentiate $f(x) = \\frac{x}{x + 1}$.',
    choices: [
      '$\\frac{1}{(x+1)^2}$',
      '$\\frac{x+1}{(x+1)^2}$',
      '$\\frac{1}{x+1}$',
      '$1$',
    ],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Quotient rule',
  },
  {
    id: 'lc-fn-deriv-h-3',
    stage: 'leaving_cert',
    strand: 'functions',
    learningOutcome: 'LC.FN.H.3: Apply the chain rule',
    b: 2,
    text: 'Differentiate $f(x) = (3x + 1)^4$.',
    choices: [
      '$12(3x + 1)^3$',
      '$4(3x + 1)^3$',
      '$3(3x + 1)^4$',
      '$(3x + 1)^3$',
    ],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Chain rule',
  },
  {
    id: 'lc-fn-deriv-h-4',
    stage: 'leaving_cert',
    strand: 'functions',
    learningOutcome: 'LC.FN.H.4: Differentiate exponential functions',
    b: 2.2,
    text: 'Differentiate $f(x) = e^{2x}$.',
    choices: ['$2e^{2x}$', '$e^{2x}$', '$2xe^{2x}$', '$e^{2}$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Derivative of exponentials',
  },
  {
    id: 'lc-fn-deriv-h-5',
    stage: 'leaving_cert',
    strand: 'functions',
    learningOutcome: 'LC.FN.H.5: Differentiate logarithmic functions',
    b: 2.2,
    text: 'Differentiate $f(x) = \\ln(x^2 + 1)$.',
    choices: [
      '$\\frac{2x}{x^2 + 1}$',
      '$\\frac{1}{x^2 + 1}$',
      '$\\frac{2x}{\\ln(x^2 + 1)}$',
      '$2x$',
    ],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Derivative of logarithms',
  },
  {
    id: 'lc-fn-maxmin-h-1',
    stage: 'leaving_cert',
    strand: 'functions',
    learningOutcome: 'LC.FN.H.6: Find stationary points of a polynomial',
    b: 2.2,
    text: 'Find the x-coordinate of the stationary point of $f(x) = x^2 - 6x + 5$.',
    choices: ['$x = 3$', '$x = -3$', '$x = 6$', '$x = 0$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Stationary points',
  },
  {
    id: 'lc-fn-maxmin-h-2',
    stage: 'leaving_cert',
    strand: 'functions',
    learningOutcome: 'LC.FN.H.7: Classify stationary points using the second derivative',
    b: 2.5,
    text: 'For $f(x) = x^3 - 3x$, classify the stationary point at $x = 1$.',
    choices: ['Local minimum', 'Local maximum', 'Point of inflection', 'Saddle point'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Second derivative test',
  },
  {
    id: 'lc-fn-int-h-1',
    stage: 'leaving_cert',
    strand: 'functions',
    learningOutcome: 'LC.FN.H.8: Compute indefinite integrals of polynomials',
    b: 2,
    text: 'Find $\\int (3x^2 + 2x) \\, dx$.',
    choices: [
      '$x^3 + x^2 + C$',
      '$x^3 + x^2$',
      '$6x + 2 + C$',
      '$x^3 + 2x^2 + C$',
    ],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Antiderivatives',
  },
  {
    id: 'lc-fn-int-h-2',
    stage: 'leaving_cert',
    strand: 'functions',
    learningOutcome: 'LC.FN.H.9: Evaluate definite integrals',
    b: 2.2,
    text: 'Evaluate $\\int_{0}^{2} 3x^2 \\, dx$.',
    choices: ['$8$', '$12$', '$6$', '$24$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Definite integrals',
  },
  {
    id: 'lc-fn-int-h-3',
    stage: 'leaving_cert',
    strand: 'functions',
    learningOutcome: 'LC.FN.H.10: Compute area under a curve',
    b: 2.5,
    text: 'Find the area between the curve $y = x^2$ and the x-axis from $x = 0$ to $x = 3$.',
    choices: ['$9$', '$3$', '$27$', '$\\frac{27}{3}$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Area under curves',
  },
  {
    id: 'lc-fn-int-h-4',
    stage: 'leaving_cert',
    strand: 'functions',
    learningOutcome: 'LC.FN.H.11: Integrate exponentials',
    b: 2.5,
    text: 'Find $\\int e^{2x} \\, dx$.',
    choices: [
      '$\\frac{1}{2} e^{2x} + C$',
      '$2 e^{2x} + C$',
      '$e^{2x} + C$',
      '$\\frac{1}{2x} e^{2x} + C$',
    ],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Integrating exponentials',
  },
  {
    id: 'lc-fn-motion-h-1',
    stage: 'leaving_cert',
    strand: 'functions',
    learningOutcome: 'LC.FN.H.12: Apply derivatives to motion problems',
    b: 2.2,
    text: 'A particle moves along a line with displacement $s(t) = t^3 - 6t^2 + 9t$. Its velocity at $t = 1$ is:',
    choices: ['$0$', '$3$', '$-3$', '$6$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Motion derivatives',
  },
  // -- LC HL: statistics_prob --
  {
    id: 'lc-sp-bin-h-1',
    stage: 'leaving_cert',
    strand: 'statistics_prob',
    learningOutcome: 'LC.SP.H.1: Apply the binomial distribution',
    b: 2,
    text: 'A fair coin is tossed $4$ times. What is the probability of exactly $2$ heads?',
    choices: ['$\\frac{6}{16}$', '$\\frac{1}{4}$', '$\\frac{1}{2}$', '$\\frac{4}{16}$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Binomial distribution',
  },
  {
    id: 'lc-sp-norm-h-1',
    stage: 'leaving_cert',
    strand: 'statistics_prob',
    learningOutcome: 'LC.SP.H.2: Use the empirical rule for the normal distribution',
    b: 2,
    text: 'For a normally distributed variable with mean $\\mu$ and standard deviation $\\sigma$, approximately what fraction of values lie within $1$ standard deviation of the mean?',
    choices: ['$50\\%$', '$68\\%$', '$95\\%$', '$99.7\\%$'],
    correctIndex: 1,
    source: 'anchor',
    khanAcademyRef: 'KA: Normal distribution',
  },
  {
    id: 'lc-sp-norm-h-2',
    stage: 'leaving_cert',
    strand: 'statistics_prob',
    learningOutcome: 'LC.SP.H.3: Compute z-scores',
    b: 2.2,
    text: 'A test has mean $70$ and standard deviation $10$. What is the z-score of a result of $85$?',
    choices: ['$1.5$', '$2$', '$0.85$', '$15$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Z-scores',
  },
  {
    id: 'lc-sp-cond-h-1',
    stage: 'leaving_cert',
    strand: 'statistics_prob',
    learningOutcome: 'LC.SP.H.4: Apply conditional probability',
    b: 2,
    text: 'In a class, $60\\%$ of students take French and $25\\%$ take both French and Spanish. Given a student takes French, what is the probability they also take Spanish?',
    choices: [
      '$\\frac{25}{60}$',
      '$\\frac{60}{25}$',
      '$\\frac{1}{4}$',
      '$\\frac{1}{2}$',
    ],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Conditional probability',
  },
  {
    id: 'lc-sp-hyp-h-1',
    stage: 'leaving_cert',
    strand: 'statistics_prob',
    learningOutcome: 'LC.SP.H.5: State a null hypothesis',
    b: 2.5,
    text: 'A researcher tests whether a new drug differs from placebo. The null hypothesis $H_0$ is best stated as:',
    choices: [
      'The drug has no effect different from placebo',
      'The drug works better than placebo',
      'The drug works worse than placebo',
      'The drug has some effect',
    ],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Hypothesis testing',
  },
  {
    id: 'lc-sp-hyp-h-2',
    stage: 'leaving_cert',
    strand: 'statistics_prob',
    learningOutcome: 'LC.SP.H.6: Interpret a p-value',
    b: 2.5,
    text: 'A test gives $p = 0.02$ at significance level $\\alpha = 0.05$. The conclusion is:',
    choices: [
      'Reject $H_0$',
      'Accept $H_0$',
      'No conclusion possible',
      'The result is not significant',
    ],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: P-values',
  },
  {
    id: 'lc-sp-corr-h-1',
    stage: 'leaving_cert',
    strand: 'statistics_prob',
    learningOutcome: 'LC.SP.H.7: Interpret a correlation coefficient',
    b: 1.8,
    text: 'A data set has correlation coefficient $r = -0.92$. Which best describes the relationship?',
    choices: [
      'Strong negative linear correlation',
      'Strong positive linear correlation',
      'Weak negative linear correlation',
      'No correlation',
    ],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Correlation coefficient',
  },
  {
    id: 'lc-sp-reg-h-1',
    stage: 'leaving_cert',
    strand: 'statistics_prob',
    learningOutcome: 'LC.SP.H.8: Apply a regression line for prediction',
    b: 2,
    text: 'A regression line is $\\hat{y} = 3x + 2$. Predict $y$ when $x = 4$.',
    choices: ['$14$', '$12$', '$11$', '$8$'],
    correctIndex: 0,
    source: 'anchor',
    khanAcademyRef: 'KA: Linear regression',
  },
];
