/**
 * Types for the post-assessment study plan feature.
 *
 * The user finishes the diagnostic, gets an AssessmentReport, then provides
 * a goal (target tier + exam date + weekly study budget). The agent fuses
 * those inputs into a StudyPlan: a per-week schedule tied to learning
 * outcomes, with milestones for each strand.
 */
import type { Strand, Tier } from './types';

/** User-supplied goal parameters collected via HITL form. */
export interface StudyPlanInput {
  /** Display name on the cover sheet. Optional — falls back to "Learner". */
  learnerName?: string;
  /** Target tier the learner wants to reach. */
  goalTier: Tier;
  /** ISO 8601 date string (YYYY-MM-DD) for the exam / target. */
  targetDate: string;
  /** Realistic weekly study budget in hours. */
  weeklyHours: number;
  /**
   * Strands to weight more heavily in the schedule. Empty = use the gap
   * analysis to prioritise automatically.
   */
  focusStrands: Strand[];
  /** Optional free-text note ("I struggle with proofs", "exam style is …"). */
  notes?: string;
}

/** A single learning outcome the learner should cover during a study block. */
export interface StudyTopic {
  strand: Strand;
  /** Curriculum LO code, e.g. "JC.AL.LIN" or "LC.AL.LOG". */
  learningOutcome: string;
  /** Plain-English topic title — what the learner sees in the plan. */
  title: string;
  /** Why this is on the plan: closing a gap, building toward goal, etc. */
  rationale: string;
  /** Hours allocated this week. */
  hours: number;
  /**
   * Practice anchor: a worked-example prompt or a reference URL.
   * Free-form so the LLM can suggest Khan Academy / past papers.
   */
  practiceHint: string;
}

/** A single week in the plan. */
export interface StudyWeek {
  /** 1-indexed week number from the start of the plan. */
  weekNumber: number;
  /** Inclusive start date of the week (YYYY-MM-DD). */
  startDate: string;
  /** Inclusive end date of the week (YYYY-MM-DD). */
  endDate: string;
  /** Theme of the week, e.g. "Algebra fundamentals" or "Mock paper week". */
  theme: string;
  /** Topics scheduled for this week. */
  topics: StudyTopic[];
  /** Concrete checkpoint ("complete 3 exam-style proofs", "100% on Khan…"). */
  milestone: string;
}

/** Per-strand priority derived from the gap between current and goal tier. */
export interface StrandPriority {
  strand: Strand;
  currentTier: Tier;
  goalTier: Tier;
  /** 0 (already at goal) → 2 (two-tier gap). Drives weekly weighting. */
  gap: 0 | 1 | 2;
  /** One sentence describing the focus for this strand across the plan. */
  focus: string;
}

/** Top-level plan document the agent emits. */
export interface StudyPlan {
  /** Echoed input for the cover sheet. */
  input: StudyPlanInput;
  /** Total weeks the plan spans (computed from targetDate). */
  totalWeeks: number;
  /** Total hours across the plan. */
  totalHours: number;
  /** Strand priorities computed deterministically from report+goal. */
  priorities: StrandPriority[];
  /** Week-by-week schedule generated by the LLM. */
  weeks: StudyWeek[];
  /** Closing summary paragraph, learner-facing. */
  summary: string;
  /** Optional caveats — e.g. "exam date < 2 weeks: focus on past papers". */
  caveats: string[];
  /** ISO timestamp when the plan was generated. */
  generatedAt: string;
}
